export enum GameState {
    OFFLINE = 0,
    AUTHENTICATED = 1,
    CONNECTING = 2,
    IN_QUEUE = 3,
    SELECTING_SERVER = 4,
    SWITCHING = 5,
    CONNECTING_TO_GAME = 6,
    SELECTING_CHARACTER = 7,
    ONLINE = 8,
}
