export enum GameState {
    OFFLINE = 0,
    AUTHENTICATED = 1,
    CONNECTING = 2,
    IN_QUEUE = 3,
    SELECTING_SERVER = 4,
    CONNECTING_TO_GAME = 5,
    SELECTING_CHARACTER = 6,
    ONLINE = 7,
}
